### ISSUE TITLE
WINE NSPA 5.9.19 build fails with MinGW on Ubuntu 20.04

### ISSUE THREAD

**Issue by rolesyuk** [nine7nine/pkgbuilds_nspa#9] opened 2020-07-28 22:02 UTC
```
x86_64-w64-mingw32-gcc -c -o process.cross.o ../../../dlls/kernelbase/process.c -I. -I../../../dlls/kernelbase \
  -I../../include -I../../../include -I../../../include/msvcrt -D__WINESRC__ -D_MSVCR_VER=0 \
  -DWINE_CROSS_PE -Wall -fno-strict-aliasing -Wdeclaration-after-statement -Wempty-body \
  -Wignored-qualifiers -Wno-packed-not-aligned -Wshift-overflow=2 -Wstrict-prototypes -Wtype-limits \
  -Wunused-but-set-parameter -Wvla -Wwrite-strings -Wpointer-arith -Wlogical-op -Wno-format \
  -Wformat-overflow -Wnonnull -gdwarf-2 -gstrict-dwarf -g -O2
echo "lz32_test.exe TESTRES \"lz32_test-stripped.exe\"" | ../../../tools/wrc/wrc -u -o ../../../programs/winetest/lz32_test.res
../../../dlls/kernelbase/process.c:24:10: fatal error: sys/resource.h: No such file or directory
   24 | #include <sys/resource.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
```
The previous version 5.9.18 builds OK.

**Comment by nine7nine** [comment] 2020-07-28 22:22
comment out this line in the pkgbuild;

  msg "Applying nspa_kernelbase-implement_SetProcessWorkingSetSize.patch"  
  patch -s -Np1 -i $srcdir/nspa_kernelbase-implement_SetProcessWorkingSetSize.patch

it'll should build after that.

MingW is your problem. I build wine the standard way on Arch, using GCC.

I can put a note or possibly add a macro so that it doesn't build that code without GCC.

**Comment by rolesyuk** [comment] 2020-07-29 08:03
I build wine the standard way on Ubuntu too: './configure && make && make install' Nothing special here from my side. MinGW indeed does not include some standard paths by default:
```
x86_64-w64-mingw32-gcc -xc -E -v -
Using built-in specs.
COLLECT_GCC=x86_64-w64-mingw32-gcc
Target: x86_64-w64-mingw32
Configured with: ../../src/configure --build=x86_64-linux-gnu --prefix=/usr --includedir='/usr/include' --mandir='/usr/share/man' --infodir='/usr/share/info' --sysconfdir=/etc --localstatedir=/var --disable-silent-rules --libdir='/usr/lib/x86_64-linux-gnu' --libexecdir='/usr/lib/x86_64-linux-gnu' --disable-maintainer-mode --disable-dependency-tracking --prefix=/usr --enable-shared --enable-static --disable-multilib --with-system-zlib --libexecdir=/usr/lib --without-included-gettext --libdir=/usr/lib --enable-libstdcxx-time=yes --with-tune=generic --with-headers=/usr/x86_64-w64-mingw32/include --enable-version-specific-runtime-libs --enable-fully-dynamic-string --enable-libgomp --enable-languages=c,c++,fortran,objc,obj-c++,ada --enable-lto --enable-threads=win32 --program-suffix=-win32 --program-prefix=x86_64-w64-mingw32- --target=x86_64-w64-mingw32 --with-as=/usr/bin/x86_64-w64-mingw32-as --with-ld=/usr/bin/x86_64-w64-mingw32-ld --enable-libatomic --enable-libstdcxx-filesystem-ts=yes --enable-dependency-tracking
Thread model: win32
gcc version 9.3-win32 20200320 (GCC) 
COLLECT_GCC_OPTIONS='-E' '-v' '-mtune=generic' '-march=x86-64'
 /usr/lib/gcc/x86_64-w64-mingw32/9.3-win32/cc1 -E -quiet -v -U_REENTRANT - -mtune=generic -march=x86-64
ignoring nonexistent directory "/usr/lib/gcc/x86_64-w64-mingw32/9.3-win32/../../../../x86_64-w64-mingw32/sys-include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/lib/gcc/x86_64-w64-mingw32/9.3-win32/include
 /usr/lib/gcc/x86_64-w64-mingw32/9.3-win32/include-fixed
 /usr/lib/gcc/x86_64-w64-mingw32/9.3-win32/../../../../x86_64-w64-mingw32/include
End of search list.
```
So the system <sys/resource.h> is not found
```
# find /usr -name resource.h | grep sys 
/usr/include/i386-linux-gnu/sys/resource.h
/usr/include/x86_64-linux-gnu/sys/resource.h
/usr/include/sys/resource.h
```

**Comment by rolesyuk** [comment] 2020-07-29 08:25
If I disable MinGW with:
```
../configure --with-mingw=no
```
wine-nspa 5.9.19 builds OK.

Looks like wine uses mingw-gcc by default if it is available. Do you have MinGW installed on your system? Does configure skips it?

Do you know what is the difference between compiling wine with x86_64-w64-mingw32-gcc and with x86_64-linux-gnu-gcc-9 -m32? Why do wine developers use x86_64-w64-mingw32-gcc by default?

**Comment by nine7nine** [comment] 2020-07-29 19:59
mingw essentially builds portable windows executables... ie: in some cases it's possible to take a wine built DLL and run it in windows. historically, also used for conformance yes, ''wine on windows'', etc... Theres also a lot of overlap between the projects, and duplication of efforts... i'm also aware of some copy-protection stuff (mostly in games), that works better with mingw.

i imagine that's why it defaults that way, if mingw is available. i can ask on wine-devel though.

that said, the actual default is to still use winegcc. it's also worth pointing out that it's also possible to build wine with clang and other compilers (none of which i will ever support).

i'm probably going to disable using mingw - as it's going to impose some restrictions that will hinder development. i also have no plans of ever using it - so allowing it's use could introduce issues that i can't reproduce... i also don't care about portability - or any of the things mentioned above.  my builds are decidedly linux only.

**Comment by nine7nine** [comment] 2020-07-29 20:01
I'll close this, when I've commuted a patch that disables mingw support

**Comment by nine7nine** [comment] 2020-07-29 20:06
https://wiki.winehq.org/Cygwin_and_More

you can read a bit about this kind of thing him the above link.

**Comment by rolesyuk** [comment] 2020-07-29 20:30
OK. I see (the documentation on this is quite sparse). If MinGW is of no use for our use case I'm going to build WINE NSPA with --with-mingw=no from now on. May be you can use the same flag in your PKGBUILD to disable mingw completely and close this.

**Comment by nine7nine** [comment] 2020-07-29 22:06
yes, lol. winehq's documentation is quite sparce and sometimes very out-of-date...

it's sometimes an inconvenience. i usually have to scour wine-devel archives, winehq forums, etc - to find info that i'm looking for (msdn a lot too)... sometimes i'll hit wine-devel (although not recently), when i'm stuck -- or i contact contributors/devs directly, if all else fails.

the upside is that most are pretty friendly/helpful, as long as you aren't wasting their time.

'yeah, i can add --with-ming=no, but i still think i'd like to disable it entirely. (probably requires commenting out a line or two in makedep. not a big deal.

**Comment by nine7nine** [comment] 2020-07-30 00:00
I'm going to close this issue - I went ahead and did what you suggested - adding --with-mingw=no.

this is an immediate solution, that should be added right away - but I'll probably still actually disable using mingw entirely.

thanks for catching this! it's appreciated.

**Closed by nine7nine** 2020-07-30 00:00 UTC
